###### Introduction to Numpy
 - Numpy array
 - Create Numpy array
 - Array methos
 - Array Indexing
 - Array Operations
 - Iteration Through array
 - Numpy matrix
 - Random number generation
 - Mathematical & Stastistical operations in numpy

##  What is Numpy in Python

Numpy is fundamental package for scientific computing in python. Using Numpy Library we can do following operations. 
  - Mathematical and logical operations on arrays
  - Fourier tranform
  - We also do operations related to linear algebra

### Data Types in Numpy
 - (bool_) boolean
 - (int_) integer type 
 - (float_)
 - (complex_)

In [1]:
## import numpy library
import numpy as np

In [2]:
## create one dimensional array
array1 = np.array([1,2,3,4])
print(array1)

[1 2 3 4]


In [4]:
array1.shape

(4,)

In [5]:
## create two or more dimensional arrays

array2 = np.array([[1,2,3,4], [5,6,7,8]])
print(array2)


[[1 2 3 4]
 [5 6 7 8]]


In [6]:
array2.shape

(2, 4)

In [7]:
## create one dimension to multiple dimensions
array3 = np.array([1,2,3,4,5,6], ndmin = 4) 
print(array3)

[[[[1 2 3 4 5 6]]]]


In [8]:
array3.shape

(1, 1, 1, 6)

In [9]:
## convert into dtype parameter
array4 = np.array([1, 2, 3, 4], dtype = complex) 
print(array4)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [10]:
## convert into dtype parameter
array4 = np.array([1, 2, 3, 4], dtype = float) 
print(array4)

[1. 2. 3. 4.]


In [11]:
## convert into dtype parameter
array4 = np.array([1, 2, 3, 4], dtype = int) 
print(array4)

[1 2 3 4]


In [14]:
## Convert list into an array
list1=[11,222,333]
ar1=np.array(list1)
ar1

array([ 11, 222, 333])

In [16]:
## covert multiple lists into array
list2=[[7,8,9],[11,21,31],[10,20,30]]
ar2=np.array(list2)
ar2

array([[ 7,  8,  9],
       [11, 21, 31],
       [10, 20, 30]])

In [17]:
ar2.shape

(3, 3)

In [18]:
 ## reshape a list in array
list3 = [1,2,3, 11,22,33,  111,222,333]
ar3=np.array(list3)
ar3

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

In [21]:
ar3 = ar3.reshape(3,3)
ar3

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [25]:
## NumPy arange() is one of the array creation routines based on numerical ranges.
## It creates sequence of numbers

np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
## it will create seqiuence of numbers with difference of 2
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [28]:
# it will create 2*2 matrics of zeros
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [32]:
# it will create 2*2 matrics of zeros
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [34]:
# it will create 2*2 matrics of 1
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [37]:
## to create 3 by 3 dignonal metrics
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
## create 10 numbers between 0 to 1 in equal parts.
num1 = np.linspace(0,1,15)
num1 

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

In [42]:
## Ex.2 on linspace
## create 100 numbers between 0 to 1 in equal parts.

num2 = np.linspace(1,2,100)
num2

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

## Numpy Matrix

In python matrix() is returns a matrix from array or string of data.and given matrix is like specialised 2D array.

In [46]:
a = np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [44]:
np.matrix([[1, 2], [3, 4]])

matrix([[1, 2],
        [3, 4]])

### Random Number Generation
We can generate random number from discrete as well as continuos distributions.
- Continuos Distributions: beta,chisquare,log normal , standard exponential, parato distributions
- Discrete Distributions:  binomial, poisson ,unifrom,hypergeometric,geometric distributions

In [47]:
import numpy as np

In [50]:
## to draw 1 random number between 1 to 7
ar2 = np.random.randint(1,7,1)
ar2

array([1])

In [53]:
## Ex of randit function
ar3 = np.random.randint(5,15,5)
ar3

array([13,  6,  5, 10, 13])

In [54]:
## generating random number from normal distribution
# random numbers mean=5 and sd=.2.
num1 = np.random.normal(5, .5, 10)   
num1

array([5.54111072, 4.6634769 , 5.02092241, 5.08908412, 5.62363533,
       4.94082509, 4.66447634, 4.76876749, 4.34305837, 4.5790422 ])

In [57]:
num1.mean()

4.923439897770544

In [62]:
# Ex.2 of generating random number from Standard normal distribution
num1 = np.random.normal(0, 1, 10)   
num1

array([-0.17438267,  0.40521614, -1.27934523,  0.36233232,  0.9146041 ,
        0.08559097,  0.68784225,  0.23733713, -0.47136899,  1.21774524])

In [63]:
num1.mean()

0.19855712524741967

In [67]:
## generate random numbers from binomial distribution
np.random.binomial(5,0.7,10)

array([2, 3, 3, 3, 5, 3, 2, 4, 3, 3])

In [50]:
## generating random number from Exponential distribution
num2 = np.random.exponential(5,10)
num2

array([0.75756563, 0.84569069, 0.96175499, 0.97777718, 8.00571106,
       1.60302796, 8.51572981, 5.28084231, 0.90245581, 1.51971946])

In [68]:
## generating random number from Possion distribution
num3 = np.random.poisson(3,10)
num3

array([ 3, 10,  4,  4,  0,  1,  4,  4,  0,  3])

In [71]:
num1?

In [72]:
## to shuffle the array
array = np.array([1,2,3,4,5,6,7,8])
np.random.shuffle(array)
print(array)

[2 3 8 1 7 6 5 4]


In [114]:
## to shuffle the array
lst = [x for x in range(10)]
array = np.array(lst)
np.random.shuffle(array)
print(array)

[8 4 7 2 9 1 5 3 0 6]


In [115]:
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### Calculating mean

In [77]:
## To calculate mean
array = np.array([1,2,3,4,5,6,7,8])
np.mean(array)

4.5

In [83]:
## Ex. of mean
array1 = np.random.normal(5,0.8,2)
array1.mean()

4.801071213641432

### Calculating Standard deviation

In [84]:
array = np.array([1,2,3,4,5,6,7,8])
array.std()

2.29128784747792

In [85]:
## Ex. of sd
array1 = np.random.normal(5,0.8,20)
array1.std()

0.5837648660978703

In [87]:
## Here we Create another array for perform some operations.
ar1 = np.array([23,7,3,14,5,66,2,8,9])
ar1 = ar1.reshape(3,3)
ar1

array([[23,  7,  3],
       [14,  5, 66],
       [ 2,  8,  9]])

In [88]:
## to calculate max. value 
ar1.max()

66

In [89]:
## to calculate min.value
ar1.min()

2

In [91]:
# to find index position where it has max. value
ar1.argmax()

5

In [92]:
# to find index position where it has min. value
ar1.argmin()

6

## Round function
The ROUND function is used to return a number rounded to a specific number of digits

In [96]:
## The ROUND function 
np.round(234.6789,1)

234.7

## Power function
 Power function is used to calculate the power raised to the base value

In [97]:
## to calculte power of specific number
np.power(7,3)

343

In [98]:
7**3

343

In [99]:
## it will calculate the absolute value of every value in the array.
np.abs(-20)

20

In [100]:
abs(-30)

30

In [101]:
## to calculate Natural logarithm of input array elements
np.log(5)

1.6094379124341003

In [106]:
## to calculate lcm value of arr1 and arr2 elements (least common multiple)
np.lcm(10,15)

30

In [108]:
## to calculate gcd value of elements ( gretest common deviser)
np.gcd(12,75)

3

In [109]:
## to calculate a square of element
np.square(5)

25

In [110]:
## to calculate a squareroot of perticular element
np.sqrt(225)

15.0

## Math Library
  Math Library provides us access to some common math functions and constants in Python

In [111]:
## import Math library
import math  

In [112]:
##  to calculate the factorial of a given number it accepts only positive number and return the factorial of number.
math.factorial(5) 

120

In [113]:
## to calculate the power of e
math.exp(5)

148.4131591025766